import type { AssetMetadataKey, AssetTemplateType } from '@/types/asset';

/**
 * Asset Field Constants
 *
 * Constants related to asset fields, validation, and limits
 */

// Constants for maximum number of auditors and mediators
export const MAX_AUDITORS = 2;
export const MAX_MEDIATORS = 2;

// Mapping of template types to their specific fields
export const TEMPLATE_FIELDS_MAP: Record<
  AssetTemplateType,
  readonly AssetMetadataKey[]
> = {
  currency: [
    'peggedCurrency',
    'pegMechanism',
    'collateralType',
    'reserveAuditor',
    'attestationFrequency',
  ],
  equity: [
    'shareClass',
    'votingRights',
    'dividendRights',
    'parValue',
    'authorizedShares',
    'liquidationPreference',
    'transferRestrictions',
  ],
  debt: [
    'debtType',
    'issueDate',
    'maturityDate',
    'couponRate',
    'couponType',
    'paymentFrequency',
    'seniority',
    'callable',
  ],
  fund: [
    'fundType',
    'fundManager',
    'managementFee',
    'performanceFee',
    'inceptionDate',
    'initialNav',
    'investmentObjective',
    'minimumInvestment',
  ],
  commodity: [
    'commodityCategory',
    'specificCommodity',
    'grade',
    'purity',
    'standardUnit',
    'deliveryLocation',
  ],
  'real-estate': [
    'propertyType',
    'propertyAddress',
    'totalValue',
    'valuationDate',
    'totalArea',
    'occupancyRate',
  ],
  derivative: [
    'derivativeType',
    'underlyingIdentifier',
    'strikePrice',
    'expirationDate',
    'settlementType',
    'contractSize',
  ],
  'structured-product': [
    'productType',
    'underlyingAssets',
    'capitalProtection',
    'barrierLevel',
    'participationRate',
    'cap',
  ],
  'credit-entitlement': [
    'creditCategory',
    'projectType',
    'vintageYear',
    'certifyingStandard',
    'registry',
    'registryId',
  ],
  basic: [
    'tokenCategory',
    'platform',
    'maxSupply',
    'initialSupply',
    'utility',
    'governanceModel',
  ],
  custom: [],
};

// All template-specific fields to clear when switching templates
export const TEMPLATE_SPECIFIC_FIELDS = [
  'maturityDate',
  'fundType',
  'underlyingAsset',
  'peggedCurrency',
  'pegMechanism',
  'collateralType',
  'reserveAuditor',
  'attestationFrequency',
  'shareClass',
  'votingRights',
  'dividendRights',
  'parValue',
  'authorizedShares',
  'liquidationPreference',
  'conversionRights',
  'transferRestrictions',
  'debtType',
  'issueDate',
  'couponRate',
  'couponType',
  'paymentFrequency',
  'dayCountConvention',
  'seniority',
  'collateral',
  'callable',
  'putable',
  'creditRating',
  'ratingAgency',
  'fundManager',
  'managementFee',
  'performanceFee',
  'inceptionDate',
  'initialNav',
  'benchmark',
  'investmentObjective',
  'assetClass',
  'minimumInvestment',
  'redemptionPeriod',
  'lockupPeriod',
  'administrator',
  'custodian',
  'auditor',
  'commodityCategory',
  'specificCommodity',
  'grade',
  'purity',
  'standardUnit',
  'tokensPerUnit',
  'deliveryLocation',
  'contractStandard',
  'assayProvider',
  'insuranceProvider',
  'auditFrequency',
  'propertyType',
  'propertyAddress',
  'propertyIdentifier',
  'totalValue',
  'valuationDate',
  'valuationFirm',
  'totalArea',
  'yearBuilt',
  'occupancyStatus',
  'occupancyRate',
  'annualRentalIncome',
  'propertyManager',
  'titleStatus',
  'encumbrances',
  'derivativeType',
  'underlyingIdentifier',
  'strikePrice',
  'expirationDate',
  'settlementType',
  'contractSize',
  'tickSize',
  'marginRequirement',
  'fundingRate',
  'exerciseStyle',
  'clearingHouse',
  'productType',
  'underlyingAssets',
  'issuePrice',
  'capitalProtection',
  'barrierLevel',
  'barrierType',
  'participationRate',
  'cap',
  'observationDates',
  'autocallTrigger',
  'payoffFormula',
  'calculationAgent',
  'creditCategory',
  'projectType',
  'vintageYear',
  'certifyingStandard',
  'geography',
  'methodology',
  'verificationBody',
  'registryId',
  'registry',
  'retirementEligible',
  'projectId',
  'tokenCategory',
  'platform',
  'utility',
  'maxSupply',
  'initialSupply',
  'supplyModel',
  'inflationRate',
  'mintingMechanism',
  'burningMechanism',
  'stakingAvailable',
  'stakingReward',
  'vestingSchedule',
  'governanceModel',
] as const;

// Standard fields that cannot be used as custom keys
export const STANDARD_FIELDS = [
  'name',
  'symbol',
  'assetType',
  'assetSubType',
  'description',
  'decimals',
  'website',
  'whitepaper',
  'metadataUri',
  'jurisdiction',
  'issuer',
  'issuerIdentifier',
  'isin',
  'cusip',
  'cins',
  'sedol',
  'figi',
  'lei',
] as const;

// Combined list of reserved keys (cannot be used as custom field keys)
export const RESERVED_KEYS = [...STANDARD_FIELDS, ...TEMPLATE_SPECIFIC_FIELDS];
